  name: monorec
  channels:
    - pytorch
    - conda-forge
    - anaconda
  dependencies:
    - python=3.8
    - pytorch
    - pytorch-lightning
    - torchvision
    - jupyter
    - tensorboard
    - tensorboardx
    - opencv
    - scipy
    - kornia
    - scikit-image
    - tqdm
    - pip
    - pip:
        - pykitti